import path from 'path';
import { fileURLToPath } from 'url';
import ExcelJS from 'exceljs';
import PDFDocument from 'pdfkit';

const __dirname = path.dirname(fileURLToPath(import.meta.url));

const BRAND = {
  primary: '1B2A4A',
  primaryRgb: [27, 42, 74],
  name: 'Verixsoft',
  logoText: 'Verixsoft',
  tagline: 'Software House',
  address: 'DHA, Lahore, Pakistan',
  // White logo — only legible on the dark header band.
  logoPath: path.join(__dirname, '../assets/verixsoft-logo.png'),
};

const PKR_FMT = '"PKR "#,##0.00';
const PCT_FMT = '0.00%';

// ── Excel helpers ────────────────────────────────────────────────────────────

function applyHeaderRow(ws, headers, rowNum = 1) {
  const row = ws.getRow(rowNum);
  headers.forEach((h, i) => {
    const cell = row.getCell(i + 1);
    cell.value = h;
    cell.font = { bold: true, color: { argb: 'FFFFFFFF' }, size: 11 };
    cell.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: `FF${BRAND.primary}` } };
    cell.border = {
      bottom: { style: 'thin', color: { argb: 'FFD0D0D0' } },
    };
    cell.alignment = { vertical: 'middle', horizontal: 'center', wrapText: true };
  });
  row.height = 20;
  ws.autoFilter = { from: { row: rowNum, column: 1 }, to: { row: rowNum, column: headers.length } };
}

function applyBrandHeader(ws, reportName, period) {
  ws.mergeCells('A1:H1');
  const titleCell = ws.getCell('A1');
  titleCell.value = BRAND.name;
  titleCell.font = { bold: true, size: 16, color: { argb: `FF${BRAND.primary}` } };
  titleCell.alignment = { horizontal: 'center' };

  ws.mergeCells('A2:H2');
  const subCell = ws.getCell('A2');
  subCell.value = `${reportName} — ${period}`;
  subCell.font = { size: 12, color: { argb: 'FF555555' } };
  subCell.alignment = { horizontal: 'center' };

  ws.getRow(3).height = 8;
}

function autoFitColumns(ws) {
  ws.columns.forEach((col) => {
    let maxLen = 10;
    col.eachCell({ includeEmpty: false }, (cell) => {
      const len = cell.value ? String(cell.value).length : 0;
      if (len > maxLen) maxLen = len;
    });
    col.width = Math.min(maxLen + 4, 50);
  });
}

function addFooter(ws, userName) {
  const lastRow = ws.lastRow?.number + 2 || ws.rowCount + 2;
  const footerCell = ws.getCell(`A${lastRow}`);
  footerCell.value = `Generated by ${userName} on ${new Date().toLocaleString('en-PK')}`;
  footerCell.font = { italic: true, color: { argb: 'FF888888' }, size: 9 };
}

// ── Revenue Excel ────────────────────────────────────────────────────────────

export async function exportRevenueExcel(
  { metrics, monthly, byClient, receivables },
  period,
  userName = 'System'
) {
  const wb = new ExcelJS.Workbook();
  wb.creator = BRAND.name;
  wb.created = new Date();

  // Sheet 1 — Summary
  const summary = wb.addWorksheet('Summary');
  applyBrandHeader(summary, 'Revenue Report', period);
  applyHeaderRow(summary, ['Metric', 'Value'], 4);
  const kpis = [
    ['MRR (Current Month)', metrics?.mrrCurrent ?? 0],
    ['ARR (Projected)', metrics?.arrProjected ?? 0],
    ['YTD Revenue', metrics?.totalRevenueYTD ?? 0],
    ['Collection Rate', (metrics?.collectionRate ?? 0) / 100],
    ['Avg Invoice Value', metrics?.avgInvoiceValue ?? 0],
    ['Avg Payment Days', metrics?.avgPaymentDays ?? 0],
  ];
  kpis.forEach(([label, val], i) => {
    const row = summary.getRow(5 + i);
    row.getCell(1).value = label;
    const valCell = row.getCell(2);
    valCell.value = val;
    if (typeof val === 'number' && val < 1 && label.includes('Rate')) {
      valCell.numFmt = PCT_FMT;
    } else if (typeof val === 'number' && label !== 'Avg Payment Days') {
      valCell.numFmt = PKR_FMT;
    }
    row.getCell(1).font = { bold: i === 0 };
  });
  summary.views = [{ state: 'frozen', ySplit: 4 }];
  autoFitColumns(summary);
  addFooter(summary, userName);

  // Sheet 2 — Monthly Breakdown
  const monthlyWs = wb.addWorksheet('Monthly Breakdown');
  applyBrandHeader(monthlyWs, 'Monthly Revenue', period);
  applyHeaderRow(monthlyWs, ['Month', 'Billed', 'Collected', 'Outstanding', 'Growth %'], 4);
  (monthly ?? []).forEach((m, i) => {
    const row = monthlyWs.getRow(5 + i);
    row.getCell(1).value = m.month;
    const billedCell = row.getCell(2);
    billedCell.value = m.billed;
    billedCell.numFmt = PKR_FMT;
    const collCell = row.getCell(3);
    collCell.value = m.collected;
    collCell.numFmt = PKR_FMT;
    const outCell = row.getCell(4);
    outCell.value = m.outstanding;
    outCell.numFmt = PKR_FMT;
    const growthCell = row.getCell(5);
    if (m.growthPercent !== undefined && m.growthPercent !== null) {
      growthCell.value = m.growthPercent / 100;
      growthCell.numFmt = PCT_FMT;
      growthCell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: m.growthPercent >= 0 ? 'FFD4EDDA' : 'FFF8D7DA' },
      };
    }
  });
  // Totals row
  const totRow = monthlyWs.getRow(5 + (monthly?.length ?? 0));
  totRow.getCell(1).value = 'TOTAL';
  totRow.getCell(1).font = { bold: true };
  totRow.getCell(2).value = (monthly ?? []).reduce((s, m) => s + m.billed, 0);
  totRow.getCell(2).numFmt = PKR_FMT;
  totRow.getCell(2).font = { bold: true };
  totRow.getCell(3).value = (monthly ?? []).reduce((s, m) => s + m.collected, 0);
  totRow.getCell(3).numFmt = PKR_FMT;
  totRow.getCell(3).font = { bold: true };
  totRow.eachCell((cell) => {
    cell.border = { top: { style: 'thin' } };
  });
  monthlyWs.views = [{ state: 'frozen', ySplit: 4 }];
  autoFitColumns(monthlyWs);
  addFooter(monthlyWs, userName);

  // Sheet 3 — By Client
  const clientWs = wb.addWorksheet('By Client');
  applyBrandHeader(clientWs, 'Revenue by Client', period);
  applyHeaderRow(
    clientWs,
    ['Rank', 'Client', 'Total Billed', 'Collected', 'Outstanding', 'Invoices', 'Projects'],
    4
  );
  (byClient ?? []).slice(0, 20).forEach((c, i) => {
    const row = clientWs.getRow(5 + i);
    row.getCell(1).value = i + 1;
    row.getCell(2).value = c.companyName ?? 'Unknown';
    const b = row.getCell(3);
    b.value = c.totalBilled;
    b.numFmt = PKR_FMT;
    const co = row.getCell(4);
    co.value = c.totalCollected;
    co.numFmt = PKR_FMT;
    const out = row.getCell(5);
    out.value = Math.max(0, c.totalBilled - c.totalCollected);
    out.numFmt = PKR_FMT;
    row.getCell(6).value = c.invoiceCount;
    row.getCell(7).value = c.projectCount;
  });
  clientWs.views = [{ state: 'frozen', ySplit: 4 }];
  autoFitColumns(clientWs);
  addFooter(clientWs, userName);

  // Sheet 4 — Receivables
  const recvWs = wb.addWorksheet('Receivables');
  applyBrandHeader(recvWs, 'Aged Receivables', period);
  applyHeaderRow(recvWs, ['Bucket', 'Invoice Count', 'Total Outstanding'], 4);
  const buckets = [
    ['Current (not overdue)', receivables?.current],
    ['1–30 days overdue', receivables?.days_30],
    ['31–60 days overdue', receivables?.days_60],
    ['61–90 days overdue', receivables?.days_90],
    ['90+ days overdue', receivables?.days_90plus],
  ];
  buckets.forEach(([label, data], i) => {
    const row = recvWs.getRow(5 + i);
    row.getCell(1).value = label;
    row.getCell(2).value = data?.count ?? 0;
    const amtCell = row.getCell(3);
    amtCell.value = data?.totalAmount ?? 0;
    amtCell.numFmt = PKR_FMT;
    if (label.includes('90+')) {
      [1, 2, 3].forEach((col) => {
        row.getCell(col).fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: 'FFF8D7DA' },
        };
      });
    }
  });
  recvWs.views = [{ state: 'frozen', ySplit: 4 }];
  autoFitColumns(recvWs);
  addFooter(recvWs, userName);

  return wb.xlsx.writeBuffer();
}

// ── Employee Excel ───────────────────────────────────────────────────────────

export async function exportEmployeeExcel(
  { employees, teamAverages: _teamAverages },
  period,
  userName = 'System'
) {
  const wb = new ExcelJS.Workbook();
  wb.creator = BRAND.name;
  wb.created = new Date();

  // Sheet 1 — Team Summary
  const teamWs = wb.addWorksheet('Team Summary');
  applyBrandHeader(teamWs, 'Employee Productivity', period);
  applyHeaderRow(
    teamWs,
    [
      'Employee',
      'Dept',
      'Tasks Assigned',
      'Tasks Done',
      'Completion %',
      'On-Time %',
      'Hours Logged',
      'Attendance %',
    ],
    4
  );
  (employees ?? []).forEach((e, i) => {
    const row = teamWs.getRow(5 + i);
    row.getCell(1).value = e.employee?.name ?? 'Unknown';
    row.getCell(2).value = e.employee?.department ?? '';
    row.getCell(3).value = e.metrics?.tasks?.tasksAssigned ?? 0;
    row.getCell(4).value = e.metrics?.tasks?.tasksCompleted ?? 0;

    const cr = e.metrics?.tasks?.completionRate;
    const crCell = row.getCell(5);
    if (cr !== null && cr !== undefined) {
      crCell.value = cr / 100;
      crCell.numFmt = PCT_FMT;
      crCell.fill = {
        type: 'pattern',
        pattern: 'solid',
        fgColor: { argb: cr >= 90 ? 'FFD4EDDA' : cr < 60 ? 'FFF8D7DA' : 'FFFFFFFF' },
      };
    }

    const otr = e.metrics?.tasks?.onTimeRate;
    const otrCell = row.getCell(6);
    if (otr !== null && otr !== undefined) {
      otrCell.value = otr / 100;
      otrCell.numFmt = PCT_FMT;
    }

    row.getCell(7).value = e.metrics?.tasks?.hoursLogged ?? 0;

    const ar = e.metrics?.attendance?.attendanceRate;
    const arCell = row.getCell(8);
    if (ar !== null && ar !== undefined) {
      arCell.value = ar / 100;
      arCell.numFmt = PCT_FMT;
      if (ar < 80) {
        arCell.fill = {
          type: 'pattern',
          pattern: 'solid',
          fgColor: { argb: 'FFFFF3CD' },
        };
      }
    }
  });
  teamWs.views = [{ state: 'frozen', ySplit: 4 }];
  autoFitColumns(teamWs);
  addFooter(teamWs, userName);

  // Sheet 2 — Task Breakdown
  const taskWs = wb.addWorksheet('Task Breakdown');
  applyBrandHeader(taskWs, 'Task Detail', period);
  applyHeaderRow(
    taskWs,
    [
      'Employee',
      'Critical',
      'High',
      'Medium',
      'Low',
      'Overdue',
      'Est. Hours',
      'Logged Hours',
      'Accuracy %',
    ],
    4
  );
  (employees ?? []).forEach((e, i) => {
    const row = taskWs.getRow(5 + i);
    const t = e.metrics?.tasks;
    row.getCell(1).value = e.employee?.name ?? 'Unknown';
    row.getCell(2).value = t?.byPriority?.critical ?? 0;
    row.getCell(3).value = t?.byPriority?.high ?? 0;
    row.getCell(4).value = t?.byPriority?.medium ?? 0;
    row.getCell(5).value = t?.byPriority?.low ?? 0;
    row.getCell(6).value = t?.overdueCount ?? 0;
    row.getCell(7).value = t?.hoursEstimated ?? 0;
    row.getCell(8).value = t?.hoursLogged ?? 0;
    if (t?.estimationAccuracy !== null && t?.estimationAccuracy !== undefined) {
      const accCell = row.getCell(9);
      accCell.value = t.estimationAccuracy / 100;
      accCell.numFmt = PCT_FMT;
    }
  });
  taskWs.views = [{ state: 'frozen', ySplit: 4 }];
  autoFitColumns(taskWs);
  addFooter(taskWs, userName);

  // Sheet 3 — Attendance Summary
  const attWs = wb.addWorksheet('Attendance Summary');
  applyBrandHeader(attWs, 'Attendance', period);
  applyHeaderRow(
    attWs,
    ['Employee', 'Present', 'Absent', 'Late', 'Working Days', 'Attendance %'],
    4
  );
  (employees ?? []).forEach((e, i) => {
    const row = attWs.getRow(5 + i);
    const a = e.metrics?.attendance;
    row.getCell(1).value = e.employee?.name ?? 'Unknown';
    row.getCell(2).value = a?.presentDays ?? 0;
    row.getCell(3).value = a?.absentDays ?? 0;
    row.getCell(4).value = a?.lateDays ?? 0;
    row.getCell(5).value = a?.workingDays ?? 0;
    if (a?.attendanceRate !== null && a?.attendanceRate !== undefined) {
      const arCell = row.getCell(6);
      arCell.value = a.attendanceRate / 100;
      arCell.numFmt = PCT_FMT;
    }
  });
  attWs.views = [{ state: 'frozen', ySplit: 4 }];
  autoFitColumns(attWs);
  addFooter(attWs, userName);

  return wb.xlsx.writeBuffer();
}

// ── Client Excel ─────────────────────────────────────────────────────────────

export async function exportClientExcel(
  { clients, leadConversion },
  period,
  userName = 'System',
  isAdmin = true
) {
  const wb = new ExcelJS.Workbook();
  wb.creator = BRAND.name;
  wb.created = new Date();

  // Sheet 1 — Client Summary
  const clientWs = wb.addWorksheet('Client Summary');
  applyBrandHeader(clientWs, 'Client Report', period);
  const clientHeaders = isAdmin
    ? [
        'Client',
        'Industry',
        'Status',
        'Total Billed',
        'Collected',
        'Outstanding',
        'Invoices',
        'Projects',
      ]
    : ['Client', 'Industry', 'Status', 'Projects', 'Active Projects'];
  applyHeaderRow(clientWs, clientHeaders, 4);

  (clients ?? []).forEach((c, i) => {
    const row = clientWs.getRow(5 + i);
    row.getCell(1).value = c.companyName ?? 'Unknown';
    row.getCell(2).value = c.industry ?? '';
    row.getCell(3).value = c.status ?? '';
    if (isAdmin) {
      const b = row.getCell(4);
      b.value = c.totalBilled ?? 0;
      b.numFmt = PKR_FMT;
      const co = row.getCell(5);
      co.value = c.totalCollected ?? 0;
      co.numFmt = PKR_FMT;
      const out = row.getCell(6);
      out.value = c.outstandingAmount ?? 0;
      out.numFmt = PKR_FMT;
      row.getCell(7).value = c.invoiceCount ?? 0;
      row.getCell(8).value = c.projectCount ?? 0;
    } else {
      row.getCell(4).value = c.projectCount ?? 0;
      row.getCell(5).value = c.activeProjects ?? 0;
    }
  });
  clientWs.views = [{ state: 'frozen', ySplit: 4 }];
  autoFitColumns(clientWs);
  addFooter(clientWs, userName);

  // Sheet 2 — Project Performance
  const projWs = wb.addWorksheet('Project Performance');
  applyBrandHeader(projWs, 'Project Performance', period);
  applyHeaderRow(
    projWs,
    ['Client', 'Project', 'Status', 'Health', 'Completion %', 'Budget', 'Actual Cost', 'On Time'],
    4
  );
  let rowIdx = 5;
  (clients ?? []).forEach((c) => {
    (c.projects ?? []).forEach((p) => {
      const row = projWs.getRow(rowIdx++);
      row.getCell(1).value = c.companyName ?? '';
      row.getCell(2).value = p.name ?? '';
      row.getCell(3).value = p.status ?? '';
      row.getCell(4).value = p.health ?? '';
      const pct = row.getCell(5);
      pct.value = (p.completionPercent ?? 0) / 100;
      pct.numFmt = PCT_FMT;
      const bud = row.getCell(6);
      bud.value = p.totalBudget ?? 0;
      bud.numFmt = PKR_FMT;
      const act = row.getCell(7);
      act.value = p.actualCost ?? 0;
      act.numFmt = PKR_FMT;
      row.getCell(8).value =
        p.deliveredOnTime === true ? 'Yes' : p.deliveredOnTime === false ? 'No' : 'N/A';
    });
  });
  projWs.views = [{ state: 'frozen', ySplit: 4 }];
  autoFitColumns(projWs);
  addFooter(projWs, userName);

  // Sheet 3 — Lead Conversion (admin only)
  if (isAdmin && leadConversion) {
    const lcWs = wb.addWorksheet('Lead Conversion');
    applyBrandHeader(lcWs, 'CONFIDENTIAL — Lead Conversion', period);
    applyHeaderRow(lcWs, ['Source', 'Total Leads', 'Converted', 'Conversion Rate'], 4);
    (leadConversion.bySource ?? []).forEach((s, i) => {
      const row = lcWs.getRow(5 + i);
      row.getCell(1).value = s.source;
      row.getCell(2).value = s.total;
      row.getCell(3).value = s.converted;
      const rateCell = row.getCell(4);
      rateCell.value = s.rate / 100;
      rateCell.numFmt = PCT_FMT;
    });
    lcWs.views = [{ state: 'frozen', ySplit: 4 }];
    autoFitColumns(lcWs);
    addFooter(lcWs, userName);
  }

  return wb.xlsx.writeBuffer();
}

// ── Attendance Excel ─────────────────────────────────────────────────────────

const HRS_FMT = '0.00';

export async function exportAttendanceExcel(
  { summary, rows, scopeLabel = 'All Employees' },
  period,
  userName = 'System'
) {
  const wb = new ExcelJS.Workbook();
  wb.creator = BRAND.name;
  wb.created = new Date();

  // Sheet 1 — Per-employee summary
  const sumWs = wb.addWorksheet('Summary');
  applyBrandHeader(sumWs, `Attendance Report (${scopeLabel})`, period);
  applyHeaderRow(
    sumWs,
    [
      'Employee',
      'Role',
      'Present',
      'Late',
      'Absent',
      'Days Logged',
      'Hours Worked',
      'Attendance %',
    ],
    4
  );
  (summary ?? []).forEach((e, i) => {
    const row = sumWs.getRow(5 + i);
    row.getCell(1).value = e.name;
    row.getCell(2).value = e.role ?? '';
    row.getCell(3).value = e.present ?? 0;
    row.getCell(4).value = e.late ?? 0;
    row.getCell(5).value = e.absent ?? 0;
    row.getCell(6).value = e.totalDays ?? 0;
    const hrs = row.getCell(7);
    hrs.value = e.totalHours ?? 0;
    hrs.numFmt = HRS_FMT;
    const ar = row.getCell(8);
    if (e.attendanceRate !== null && e.attendanceRate !== undefined) {
      ar.value = e.attendanceRate / 100;
      ar.numFmt = PCT_FMT;
      if (e.attendanceRate < 80) {
        ar.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFF3CD' } };
      }
    }
  });
  sumWs.views = [{ state: 'frozen', ySplit: 4 }];
  autoFitColumns(sumWs);
  addFooter(sumWs, userName);

  // Sheet 2 — Daily log
  const logWs = wb.addWorksheet('Daily Log');
  applyBrandHeader(logWs, 'Attendance — Daily Log', period);
  applyHeaderRow(
    logWs,
    ['Date', 'Employee', 'Role', 'Check In', 'Check Out', 'Hours', 'Status', 'IP Address'],
    4
  );
  (rows ?? []).forEach((r, i) => {
    const row = logWs.getRow(5 + i);
    row.getCell(1).value = r.date;
    row.getCell(2).value = r.name;
    row.getCell(3).value = r.role ?? '';
    row.getCell(4).value = r.checkIn ?? '--';
    row.getCell(5).value = r.checkOut ?? '--';
    const hrs = row.getCell(6);
    hrs.value = r.hours ?? 0;
    hrs.numFmt = HRS_FMT;
    const st = row.getCell(7);
    st.value = r.status ?? '';
    if (r.status === 'late') {
      st.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFFFF3CD' } };
    } else if (r.status === 'absent') {
      st.fill = { type: 'pattern', pattern: 'solid', fgColor: { argb: 'FFF8D7DA' } };
    }
    row.getCell(8).value = r.ipAddress ?? '';
  });
  logWs.views = [{ state: 'frozen', ySplit: 4 }];
  autoFitColumns(logWs);
  addFooter(logWs, userName);

  return wb.xlsx.writeBuffer();
}

// ── PDF helpers ──────────────────────────────────────────────────────────────

function pdfCoverPage(doc, reportTitle, period, generatedBy) {
  doc.rect(0, 0, doc.page.width, 200).fill(BRAND.primaryRgb);
  doc.fillColor('white').fontSize(28).font('Helvetica-Bold').text(BRAND.name, 50, 60);
  doc.fontSize(16).font('Helvetica').text(reportTitle, 50, 100);
  doc.fontSize(12).text(period, 50, 125);
  doc
    .fillColor('#333333')
    .fontSize(10)
    .font('Helvetica')
    .text(`Generated by: ${generatedBy}`, 50, 220);
  doc.text(`Generated at: ${new Date().toLocaleString('en-PK')}`, 50, 235);
}

function pdfSectionHeader(doc, title) {
  doc.moveDown(1);
  doc.rect(doc.x, doc.y, doc.page.width - 100, 22).fill(BRAND.primaryRgb);
  doc
    .fillColor('white')
    .fontSize(12)
    .font('Helvetica-Bold')
    .text(title, doc.x + 5, doc.y - 18);
  doc.fillColor('#333333').font('Helvetica').fontSize(10);
  doc.moveDown(0.5);
}

function pdfTable(doc, headers, rows, opts = {}) {
  const colWidths = opts.colWidths ?? headers.map(() => (doc.page.width - 100) / headers.length);
  const startX = doc.x;
  let y = doc.y;

  // Header
  doc.font('Helvetica-Bold').fontSize(9);
  headers.forEach((h, i) => {
    doc
      .rect(startX + colWidths.slice(0, i).reduce((s, w) => s + w, 0), y, colWidths[i], 18)
      .fill([220, 220, 240]);
    doc
      .fillColor('#333333')
      .text(h, startX + colWidths.slice(0, i).reduce((s, w) => s + w, 0) + 2, y + 4, {
        width: colWidths[i] - 4,
        ellipsis: true,
      });
  });
  y += 20;

  // Rows
  doc.font('Helvetica').fontSize(9);
  rows.forEach((row, ri) => {
    if (y > doc.page.height - 80) {
      doc.addPage();
      y = 50;
    }
    const bg = ri % 2 === 0 ? [255, 255, 255] : [248, 248, 252];
    doc
      .rect(
        startX,
        y,
        colWidths.reduce((s, w) => s + w, 0),
        16
      )
      .fill(bg);
    row.forEach((cell, i) => {
      doc
        .fillColor('#333333')
        .text(
          String(cell ?? ''),
          startX + colWidths.slice(0, i).reduce((s, w) => s + w, 0) + 2,
          y + 3,
          { width: colWidths[i] - 4, ellipsis: true }
        );
    });
    y += 18;
  });
  doc.y = y;
}

function pkr(n) {
  return `PKR ${Number(n ?? 0).toLocaleString('en-PK', { minimumFractionDigits: 2 })}`;
}

function pct(n) {
  return n !== null && n !== undefined ? `${Number(n).toFixed(2)}%` : 'N/A';
}

// ── Invoice PDF ──────────────────────────────────────────────────────────────

/**
 * Render a single invoice to a branded PDF buffer.
 * Expects a populated invoice (client + project) as a plain object.
 */
export function exportInvoicePdf(invoice, generatedBy = 'System') {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks = [];
    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const currency = invoice.currency || 'PKR';
    const money = (n) =>
      `${currency} ${Number(n ?? 0).toLocaleString('en-PK', { minimumFractionDigits: 2 })}`;
    const date = (d) => (d ? new Date(d).toLocaleDateString('en-PK') : '—');

    const client = invoice.client || {};
    const primaryContact =
      (client.contacts || []).find((c) => c.isPrimary) || (client.contacts || [])[0] || {};

    // Header band — dark so the white Verixsoft logo reads cleanly.
    doc.rect(0, 0, doc.page.width, 120).fill(BRAND.primaryRgb);

    // Logo (left) + company name beside it. Logo is best-effort: if the asset
    // is missing we fall back to a text-only lockup rather than failing.
    let nameX = 50;
    try {
      doc.image(BRAND.logoPath, 50, 35, { width: 50, height: 50 });
      nameX = 112;
    } catch {
      // no logo asset — keep the name flush-left
    }
    doc.fillColor('white').fontSize(24).font('Helvetica-Bold').text(BRAND.name, nameX, 42);
    doc
      .fontSize(10)
      .font('Helvetica')
      .fillColor('#C7D0E0')
      .text(`${BRAND.tagline} · ${BRAND.address}`, nameX, 74);

    doc
      .fontSize(28)
      .font('Helvetica-Bold')
      .fillColor('white')
      .text('INVOICE', 0, 42, { align: 'right', width: doc.page.width - 50 });
    doc
      .fontSize(11)
      .font('Helvetica')
      .text(`#${invoice.invoiceNumber}`, 0, 78, { align: 'right', width: doc.page.width - 50 });

    doc.fillColor('#333333');

    // Meta: bill-to + dates
    let y = 150;
    doc.font('Helvetica-Bold').fontSize(10).text('BILL TO', 50, y);
    doc.font('Helvetica').fontSize(11);
    doc.text(client.companyName || 'Client', 50, y + 16);
    if (primaryContact.name) doc.text(primaryContact.name, 50, y + 32);
    if (primaryContact.email) doc.text(primaryContact.email, 50, y + 48);

    const rightX = 330;
    doc.font('Helvetica-Bold').fontSize(10).text('DETAILS', rightX, y);
    doc.font('Helvetica').fontSize(10);
    doc.text(`Status: ${String(invoice.status || 'draft').toUpperCase()}`, rightX, y + 16);
    doc.text(`Issued: ${date(invoice.sentAt || invoice.createdAt)}`, rightX, y + 32);
    doc.text(`Due: ${date(invoice.dueDate)}`, rightX, y + 48);
    if (invoice.project?.name) doc.text(`Project: ${invoice.project.name}`, rightX, y + 64);

    // Line items table
    doc.y = y + 96;
    doc.x = 50;
    pdfTable(
      doc,
      ['Description', 'Qty', 'Unit Price', 'Amount'],
      (invoice.lineItems || []).map((it) => [
        it.description,
        it.quantity,
        money(it.unitPrice),
        money((it.quantity || 0) * (it.unitPrice || 0)),
      ]),
      { colWidths: [250, 50, 100, 100] }
    );

    // Totals
    doc.moveDown(1);
    const totals = [
      ['Subtotal', money(invoice.subtotal)],
      ...(invoice.discountAmount
        ? [[`Discount (${invoice.discountPercent || 0}%)`, `- ${money(invoice.discountAmount)}`]]
        : []),
      ...(invoice.taxAmount
        ? [[`Tax (${invoice.taxPercent || 0}%)`, money(invoice.taxAmount)]]
        : []),
      ['Total', money(invoice.total)],
      ['Paid', money(invoice.paidAmount)],
      ['Amount Due', money(Math.max(0, (invoice.total || 0) - (invoice.paidAmount || 0)))],
    ];
    const tx = 330;
    let ty = doc.y;
    totals.forEach(([label, val]) => {
      const isTotal = label === 'Total' || label === 'Amount Due';
      doc.font(isTotal ? 'Helvetica-Bold' : 'Helvetica').fontSize(isTotal ? 12 : 10);
      doc.fillColor('#333333').text(label, tx, ty, { width: 110 });
      doc.text(val, tx + 110, ty, { width: 105, align: 'right' });
      ty += isTotal ? 20 : 16;
    });

    if (invoice.notes) {
      doc.moveDown(2);
      doc
        .font('Helvetica-Bold')
        .fontSize(10)
        .text('Notes', 50, ty + 16);
      doc
        .font('Helvetica')
        .fontSize(10)
        .fillColor('#555555')
        .text(invoice.notes, 50, ty + 32, {
          width: doc.page.width - 100,
        });
    }

    // Footer pinned to the bottom of the current page. Temporarily drop the
    // bottom margin so PDFKit doesn't spill the footer onto a fresh page.
    const savedBottom = doc.page.margins.bottom;
    doc.page.margins.bottom = 0;
    doc
      .fontSize(9)
      .fillColor('#888888')
      .font('Helvetica-Oblique')
      .text(
        `${BRAND.name} · ${BRAND.tagline}  —  Generated by ${generatedBy} on ${new Date().toLocaleString('en-PK')}`,
        50,
        doc.page.height - 50,
        { align: 'center', width: doc.page.width - 100, lineBreak: false }
      );
    doc.page.margins.bottom = savedBottom;

    doc.end();
  });
}

// ── Revenue PDF ──────────────────────────────────────────────────────────────

export function exportRevenuePdf(
  { metrics, monthly, byClient, byType },
  period,
  generatedBy = 'System'
) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks = [];
    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    // Cover page
    pdfCoverPage(doc, 'Revenue Analytics Report', period, generatedBy);

    // Page 2 — Executive Summary
    doc.addPage();
    pdfSectionHeader(doc, 'Executive Summary');
    doc.moveDown(0.5);
    pdfTable(
      doc,
      ['Metric', 'Value'],
      [
        ['MRR (Current Month)', pkr(metrics?.mrrCurrent)],
        ['ARR (Projected)', pkr(metrics?.arrProjected)],
        ['YTD Revenue', pkr(metrics?.totalRevenueYTD)],
        ['Collection Rate', pct(metrics?.collectionRate)],
        ['Avg Invoice Value', pkr(metrics?.avgInvoiceValue)],
        ['Avg Payment Days', `${metrics?.avgPaymentDays ?? 0} days`],
      ],
      { colWidths: [250, 200] }
    );

    // Page 3 — Monthly Revenue Table
    doc.addPage();
    pdfSectionHeader(doc, 'Monthly Revenue Breakdown');
    doc.moveDown(0.5);
    pdfTable(
      doc,
      ['Month', 'Billed', 'Collected', 'Outstanding'],
      (monthly ?? []).map((m) => [m.month, pkr(m.billed), pkr(m.collected), pkr(m.outstanding)]),
      { colWidths: [90, 140, 140, 130] }
    );

    // Page 4 — Top clients + by type
    doc.addPage();
    pdfSectionHeader(doc, 'Top 10 Clients by Revenue');
    doc.moveDown(0.5);
    pdfTable(
      doc,
      ['Rank', 'Client', 'Collected', 'Billed', 'Invoices'],
      (byClient ?? [])
        .slice(0, 10)
        .map((c, i) => [
          i + 1,
          c.companyName ?? 'Unknown',
          pkr(c.totalCollected),
          pkr(c.totalBilled),
          c.invoiceCount,
        ]),
      { colWidths: [40, 160, 110, 110, 80] }
    );

    if ((byType ?? []).length > 0) {
      doc.moveDown(1);
      pdfSectionHeader(doc, 'Revenue by Project Type');
      doc.moveDown(0.5);
      pdfTable(
        doc,
        ['Type', 'Projects', 'Collected'],
        (byType ?? []).map((t) => [
          Array.isArray(t.type) ? t.type.join(', ') : t.type || 'Untagged',
          t.projectCount,
          pkr(t.totalCollected),
        ]),
        { colWidths: [200, 100, 200] }
      );
    }

    doc.end();
  });
}

// ── Employee PDF ─────────────────────────────────────────────────────────────

export function exportEmployeePdf(
  { employees, teamAverages: _teamAverages, single },
  period,
  generatedBy = 'System'
) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks = [];
    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    pdfCoverPage(doc, 'Employee Productivity Report', period, generatedBy);

    doc.addPage();
    pdfSectionHeader(doc, 'Team Summary');
    doc.moveDown(0.5);
    pdfTable(
      doc,
      ['Employee', 'Dept', 'Done', 'Comp%', 'OT%', 'Hours', 'Att%'],
      (employees ?? []).map((e) => [
        e.employee?.name ?? 'Unknown',
        e.employee?.department ?? '',
        e.metrics?.tasks?.tasksCompleted ?? 0,
        pct(e.metrics?.tasks?.completionRate),
        pct(e.metrics?.tasks?.onTimeRate),
        e.metrics?.tasks?.hoursLogged ?? 0,
        pct(e.metrics?.attendance?.attendanceRate),
      ]),
      { colWidths: [110, 70, 40, 55, 55, 55, 55] }
    );

    if (single && employees?.length === 1) {
      const e = employees[0];
      doc.addPage();
      pdfSectionHeader(doc, `Individual Report: ${e.employee?.name}`);
      doc.moveDown(0.5);
      pdfTable(
        doc,
        ['Metric', 'Value'],
        [
          ['Tasks Assigned', e.metrics?.tasks?.tasksAssigned ?? 0],
          ['Tasks Completed', e.metrics?.tasks?.tasksCompleted ?? 0],
          ['Completion Rate', pct(e.metrics?.tasks?.completionRate)],
          ['On-Time Rate', pct(e.metrics?.tasks?.onTimeRate)],
          ['Hours Logged', e.metrics?.tasks?.hoursLogged ?? 0],
          ['Attendance Rate', pct(e.metrics?.attendance?.attendanceRate)],
          ['Present Days', e.metrics?.attendance?.presentDays ?? 0],
          ['Absent Days', e.metrics?.attendance?.absentDays ?? 0],
          ['Late Days', e.metrics?.attendance?.lateDays ?? 0],
        ],
        { colWidths: [250, 200] }
      );
    }

    doc.end();
  });
}

// ── Attendance PDF ───────────────────────────────────────────────────────────

export function exportAttendancePdf(
  { summary, rows, scopeLabel = 'All Employees' },
  period,
  generatedBy = 'System'
) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks = [];
    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    pdfCoverPage(doc, `Attendance Report — ${scopeLabel}`, period, generatedBy);

    // Page 2 — Per-employee summary
    doc.addPage();
    pdfSectionHeader(doc, 'Employee Summary');
    doc.moveDown(0.5);
    pdfTable(
      doc,
      ['Employee', 'Role', 'Present', 'Late', 'Absent', 'Hours', 'Att%'],
      (summary ?? []).map((e) => [
        e.name,
        e.role ?? '',
        e.present ?? 0,
        e.late ?? 0,
        e.absent ?? 0,
        Number(e.totalHours ?? 0).toFixed(2),
        pct(e.attendanceRate),
      ]),
      { colWidths: [130, 80, 55, 45, 50, 60, 60] }
    );

    // Page 3 — Daily log
    doc.addPage();
    pdfSectionHeader(doc, 'Daily Log');
    doc.moveDown(0.5);
    pdfTable(
      doc,
      ['Date', 'Employee', 'In', 'Out', 'Hours', 'Status'],
      (rows ?? []).map((r) => [
        r.date,
        r.name,
        r.checkIn ?? '--',
        r.checkOut ?? '--',
        Number(r.hours ?? 0).toFixed(2),
        r.status ?? '',
      ]),
      { colWidths: [90, 140, 60, 60, 50, 70] }
    );

    doc.end();
  });
}

// ── Client PDF ───────────────────────────────────────────────────────────────

export function exportClientPdf(
  { clients, leadConversion: _leadConversion, single },
  period,
  generatedBy = 'System',
  isAdmin = true
) {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const chunks = [];
    doc.on('data', (c) => chunks.push(c));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    pdfCoverPage(doc, 'Client Reports', period, generatedBy);

    doc.addPage();
    pdfSectionHeader(doc, 'Client List Summary');
    doc.moveDown(0.5);

    const headers = isAdmin
      ? ['Client', 'Industry', 'Collected', 'Outstanding', 'Projects']
      : ['Client', 'Industry', 'Status', 'Projects'];
    const rows = (clients ?? []).map((c) =>
      isAdmin
        ? [
            c.companyName ?? 'Unknown',
            c.industry ?? '',
            pkr(c.totalCollected),
            pkr(c.outstandingAmount),
            c.projectCount ?? 0,
          ]
        : [c.companyName ?? 'Unknown', c.industry ?? '', c.status ?? '', c.projectCount ?? 0]
    );
    pdfTable(doc, headers, rows, {
      colWidths: isAdmin ? [140, 90, 110, 110, 50] : [170, 110, 80, 60],
    });

    if (isAdmin && single && clients?.length === 1) {
      const c = clients[0];
      doc.addPage();
      doc.rect(20, 20, doc.page.width - 40, 24).fill([255, 230, 230]);
      doc
        .fillColor('#CC0000')
        .fontSize(10)
        .font('Helvetica-Bold')
        .text('CONFIDENTIAL — Admin Only', 25, 26);
      doc.fillColor('#333333').font('Helvetica');

      pdfSectionHeader(doc, `Financial Summary: ${c.companyName}`);
      doc.moveDown(0.5);
      pdfTable(
        doc,
        ['Metric', 'Value'],
        [
          ['Total Billed', pkr(c.totalBilled)],
          ['Total Collected', pkr(c.totalCollected)],
          ['Outstanding', pkr(c.outstandingAmount)],
          ['Invoice Count', c.invoiceCount ?? 0],
          ['Avg Payment Days', `${c.avgPaymentDays ?? 'N/A'} days`],
        ],
        { colWidths: [250, 200] }
      );

      if ((c.projects ?? []).length > 0) {
        doc.moveDown(1);
        pdfSectionHeader(doc, 'Project Performance');
        doc.moveDown(0.5);
        pdfTable(
          doc,
          ['Project', 'Status', 'Health', 'Completion', 'On Time'],
          c.projects.map((p) => [
            p.name ?? '',
            p.status ?? '',
            p.health ?? '',
            pct(p.completionPercent),
            p.deliveredOnTime === true ? 'Yes' : p.deliveredOnTime === false ? 'No' : 'N/A',
          ]),
          { colWidths: [150, 80, 60, 90, 60] }
        );
      }
    }

    doc.end();
  });
}
